-- hotboards: store board metadata
create table if not exists public.hotboards (
  id bigint generated by default as identity primary key,
  hashid text not null unique,
  name text not null,
  display text not null,
  domain text not null,
  logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- hotitems: store board items
create table if not exists public.hotitems (
  id bigint generated by default as identity primary key,
  hashid text not null,
  rank int not null,
  title text not null,
  description text,
  url text not null,
  thumbnail text,
  extra text,
  hot_value int not null default 0,
  collected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hotitems_hashid_url_unique unique (hashid, url),
  constraint hotitems_hashid_fk foreign key (hashid) references public.hotboards(hashid) on delete cascade
);

-- Useful indexes
create index if not exists hotitems_hashid_rank_idx on public.hotitems (hashid, rank);
create index if not exists hotitems_collected_at_idx on public.hotitems (collected_at desc);


