-- hotboards: store board metadata
create table if not exists public.hotboards (
  id bigint generated by default as identity primary key,
  hashid text not null unique,
  name text not null,
  display text not null,
  domain text not null,
  logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- hotitems: store board items
create table if not exists public.hotitems (
  id bigint generated by default as identity primary key,
  hashid text not null,
  rank int not null,
  title text not null,
  description text,
  url text not null,
  thumbnail text,
  extra text,
  hot_value int not null default 0,
  collected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hotitems_hashid_url_unique unique (hashid, url),
  constraint hotitems_hashid_fk foreign key (hashid) references public.hotboards(hashid) on delete cascade
);

-- 素材库表：存储从热榜添加到素材库的内容
create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  source_url text not null,
  source_platform text not null,
  source_hashid text,
  source_rank int,
  source_hot_value int,
  thumbnail text,
  extra_data jsonb,
  status text not null default 'active', -- active, archived, deleted
  tags text[],
  category text,
  user_id text, -- 预留用户ID字段，支持多用户
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- AI改写任务表：记录AI改写的状态和结果
create table if not exists public.ai_rewrite_tasks (
  id bigint generated by default as identity primary key,
  material_id bigint not null,
  status text not null default 'pending', -- pending, processing, completed, failed
  original_content text not null,
  rewritten_content text,
  rewrite_style text not null default 'professional',
  rewrite_prompt text,
  error_message text,
  processing_started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_rewrite_tasks_material_id_fk foreign key (material_id) references public.materials(id) on delete cascade
);

-- 改写结果表：存储AI改写的详细结果
create table if not exists public.rewrite_results (
  id bigint generated by default as identity primary key,
  task_id bigint not null,
  material_id bigint not null,
  original_title text not null,
  rewritten_title text,
  original_description text,
  rewritten_description text,
  original_content text,
  rewritten_content text,
  rewrite_style text not null,
  quality_score numeric(3,2), -- 0.00-1.00
  word_count int,
  processing_time_ms int,
  created_at timestamptz not null default now(),
  constraint rewrite_results_task_id_fk foreign key (task_id) references public.ai_rewrite_tasks(id) on delete cascade,
  constraint rewrite_results_material_id_fk foreign key (material_id) references public.materials(id) on delete cascade
);

-- Useful indexes
create index if not exists hotitems_hashid_rank_idx on public.hotitems (hashid, rank);
create index if not exists hotitems_collected_at_idx on public.hotitems (collected_at desc);

-- 新增索引
create index if not exists materials_source_url_idx on public.materials (source_url);
create index if not exists materials_status_idx on public.materials (status);
create index if not exists materials_user_id_idx on public.materials (user_id);
create index if not exists materials_created_at_idx on public.materials (created_at desc);

create index if not exists ai_rewrite_tasks_material_id_idx on public.ai_rewrite_tasks (material_id);
create index if not exists ai_rewrite_tasks_status_idx on public.ai_rewrite_tasks (status);
create index if not exists ai_rewrite_tasks_created_at_idx on public.ai_rewrite_tasks (created_at desc);

create index if not exists rewrite_results_task_id_idx on public.rewrite_results (task_id);
create index if not exists rewrite_results_material_id_idx on public.rewrite_results (material_id);


